### ISSUE TITLE
Contracts listing (EPG get_all_consumed does not list all entries)

### ISSUE THREAD

**Issue by irr** [datacenter/acitoolkit#125] opened 2015-09-02 19:08 UTC
I am trying to list every contract related to an EPG, and I can't list contracts from another tenant (like 'common'). Let me explain in more details:

My lab: I have a tenant 'test' with an EPG (epg_test1) consuming two contracts. The first one, 'web' was created inside 'test' tenant. The other one 'myssh' was created inside 'common' tenant to be used in every new tenant if needed. My environment is listed bellow:
```shell
(dev)$ pip freeze|grep aci
acicobra==1.1-1o
acimodel==1.1-1o
acitoolkit==0.3.1
(dev)$ python -V
Python 2.7.6
```

Listing 'consumed' contracts:

```python
t = Tenant.get_deep(session, names=('test',))[0]
o = Search()
o.name = 'epg_test1'
e = t.find(o)[0] # EPG
for c in e.get_all_consumed():
    print c.name
```

If I run the code above, I have the following output:
```shell
> web
```

If run the similar code using the cobra sdk, I get all (consumed) contracts related with the EPG including the common contracts (see bellow):

```python
moDir = MoDirectory(session)
moDir.login()
dnQuery = DnQuery("uni/tn-test/ap-app_test/epg-epg_test1")
dnQuery.subtree = 'children'
dnQuery.queryTarget = 'subtree'
dnQuery.classFilter = "fvRsCons"
rsMo = moDir.query(dnQuery)
for o in rsMo:
    print o.tDn
```

If I run the code above, I have the following output:
```shell
> uni/tn-test/brc-web
> uni/tn-common/brc-myssh
```

Am I doing something wrong? Am I missing something with the acitoolkit code?

Regards,

   Ivan

**Comment by dnq** [comment] 2015-09-02 19:10
Hi Ivan,

As always, a very clear error description :-)
I have a look into this.

Regards
Richy

**Comment by dnq** [comment] 2015-09-02 19:45
Problem is related to different code pieces, here you can see an example (acitoolkit.py :860)
```
elif 'fvRsCons' in child:
                contract_name = child['fvRsCons']['attributes']['tnVzBrCPName']
                contract_search = Search()
                contract_search.name = contract_name
                objs = tenant.find(contract_search)
                for contract in objs:
                    if isinstance(contract, Contract):
                        self.consume(contract)
```
Only Contracts that are found in the 'current' Tenant (On which you call .get_deep()) are consumed by the EPGs of this Tenant.

Possible fix could be to search other tenants if the Contract is not found in the current one. I could try to fix it, but would be good to hear a comment from @michsmit99 @Edsall, maybe there is another way to resolve this 'inter Tenant' relationships?

Regards
Richy

**Comment by michsmit99** [comment] 2015-09-03 00:48
The cross-tenant code is fairly recent and still has some holes. For instance, the ContractInterface support was added fairly recently but get_deep currently doesn't walk the relationships across tenants. I think Richy is on the right track with checking other tenants. In the case of consuming/providing contracts, this is somewhat simpler since we should be able to just check tenant common.  Maybe, we can always grab tenant common as well as the specified tenant (or at least have an optional parameter) ?

**Comment by dnq** [comment] 2015-09-06 21:03
Thanks for the input Michael.
I have a hard time to find a 'simple' solution here :-)

Maybe you can give me a push in the right direction, but currently the issue is that the 'common' Tenant Object doesn't exist if i do something like 't = Tenant.get_deep(session, names=('test',))[0]', so i can't search this Object for Contracts. One Solution could be that we always create the 'common' Tenant with the '.get_deep' call, but this looks a bit like a hack?

**Comment by irr** [comment] 2015-09-07 10:04
Hi Richy,
Maybe you can create it and walk the relationships across tenants passed in arguments as shown below:
```python
t = Tenant.get_deep(session, names=('test','common'))[0]
```
Regards,
  Ivan

**Comment by michsmit99** [comment] 2015-09-15 19:34
I just checked in some code that will implement what Ivan is suggesting. It leverages the Fabric class so that we can walk up the tree to find tenant common if the contract is not found in the current tenant. It will get tenant common first and then get the other tenants listed. Here's an example code snippet:

    fabric = Fabric()
    tenants = Tenant.get_deep(session, names=['test', 'common'], parent=fabric)

**Comment by irr** [comment] 2015-09-16 14:52
Thanks Michael! I tested and everything is working now.

**Closed** 2015-10-08 14:18 UTC
